# Generated by Django 4.2.9 on 2024-01-10 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(help_text='author name', max_length=100)),
                ('lastName', models.CharField(help_text='author name', max_length=100)),
                ('date_of_birth', models.DateField(help_text='date of birth')),
                ('date_of_dith', models.DateField(help_text='date of dith', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Geneger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='gene name', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='gene name', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='book title', max_length=100)),
                ('isbn', models.CharField(help_text='ISBN', max_length=100)),
                ('summery', models.TextField(help_text='book summ', max_length=1000)),
                ('author', models.ForeignKey(help_text='author', on_delete=django.db.models.deletion.CASCADE, to='bookMangment.author')),
                ('gener', models.ManyToManyField(help_text='geneger', to='bookMangment.geneger')),
            ],
        ),
    ]
