# Generated by Django 4.2.9 on 2024-01-10 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookMangment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(help_text='author', null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookMangment.author'),
        ),
    ]
