# Generated by Django 4.2.9 on 2024-01-17 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookMangment', '0006_alter_author_date_of_birth_alter_author_date_of_dith'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='date_of_birth',
            field=models.DateField(default='2024-01-15', help_text='date of birth'),
            preserve_default=False,
        ),
    ]
