# Generated by Django 4.2.9 on 2024-01-17 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookMangment', '0007_alter_author_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='date_of_birth',
            field=models.DateField(help_text='date of birth', null=True),
        ),
    ]
