# Generated by Django 4.2.9 on 2024-01-24 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookMangment', '0009_bookinstance_brower'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinstance',
            name='loanPrice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
