# Generated by Django 4.2.9 on 2024-01-26 15:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookMangment', '0010_bookinstance_loanprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('youtube_playlist_id', models.CharField(max_length=200)),
                ('users', models.ManyToManyField(related_name='playlists', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
